"""empty message

Revision ID: 08084a992d8b
Revises: 
Create Date: 2018-03-23 09:28:07.017990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08084a992d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('hash_key', sa.String(), nullable=False),
    sa.Column('activate', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hash_key'),
    sa.UniqueConstraint('username')
    )
    op.create_table('diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diaries_category'), 'diaries', ['category'], unique=False)
    op.create_index(op.f('ix_diaries_location'), 'diaries', ['location'], unique=False)
    op.create_index(op.f('ix_diaries_name'), 'diaries', ['name'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_index(op.f('ix_diaries_name'), table_name='diaries')
    op.drop_index(op.f('ix_diaries_location'), table_name='diaries')
    op.drop_index(op.f('ix_diaries_category'), table_name='diaries')
    op.drop_table('diaries')
    op.drop_table('users')
    # ### end Alembic commands ###
